### ISSUE TITLE
[S3][TransferUtility] Key names with special characters are not supported

### ISSUE THREAD

**Issue by rickymohk** [aws-amplify/aws-sdk-android#526]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS S3
* In what version of SDK are you facing the problem?
2.6.30
* Is the issue limited to Simulators / Actual Devices?
no
* Can your problem be resolved if you bump to a higher version of SDK?
no
* Is this problem related to specific Android/OS version?
no
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Upload a file with key name "abc@def.com" using TransferUtility.
With sdk version 2.2.18, the key name appears correctly as "abc@def.com" on s3.
With sdk version 2.6.30, the key name becomes "abc%40def.com" on s3.

* Please include a stacktrace if applicable.

I want the key name not get automatically url encoded. Is staying in lower sdk version the only way to accomplish? However, I have to bump to 2.6.30 due to API level 28 Apache Commons Logging issue. Please help. 
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
@rickymohk Sorry for the inconvenience caused. This issue has been fixed in 2.7.4. Please update your app and see if it fixes the issue.

**Comment by Huolju** [comment]
@kvasukib Actually, in a putObject the key is still encoded in AmazonS3Client.resolveRequestEndpoint and in HttpUtils.appendUri so the problem is still there.

![image](https://user-images.githubusercontent.com/2774525/47309093-6ba67480-d5e8-11e8-9166-557946783824.png)

**Comment by kvasukib** [comment]
@Huolju Sorry for the inconvenience caused. We are looking into fixing it. Currently the SDK uses the URLEncoder to encode the URL with the key name in it and un-encodes (escapes) certain characters. What is the key you are trying to upload?

**Comment by Huolju** [comment]
@kvasukib Hi thanks for the quick answer, workgroup/538920374@edit.symbol.

**Comment by Daxito** [comment]
Also facing the same issue here, I hope there is a fix soon

**Comment by kvasukib** [comment]
@rickymohk @Huolju @mUfoq @Daxito We have fixed this issue in `2.11.0` version of the SDK. The fix includes removal of the additional layer of encoding and escaping done by the `AmazonS3Client`. Hence this change requires testing on your end before upgrading your app with the new SDK.

Please read our [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/blob/master/CHANGELOG.md#release-2110) and [Documentation](https://aws-amplify.github.io/docs/android/storage#supporting-unicode-characters-in-key-names) for detailed information on the change.

Please let us know if you have any further questions/comments on the fix.

**Comment by rickymohk** [comment]
The fix works. Thank you very much.

**Comment by muellerfr** [comment]
@rickymohk, excellent, thank you for confirming. We'll leave this issue open for a few more days, so others can respond also.

**Comment by muellerfr** [comment]
@rickymohk @Huolju @mUfoq @Daxito - I am going ahead and closing this issue as @rickymohk confirmed that the fix worked for him. Please open another issue if you are still experiencing problems.
