### ISSUE TITLE
awsconfiguration.json missing from ./src/main/res/raw

### ISSUE THREAD

**Issue by virtualprodigy** [aws-amplify/aws-sdk-android#578]
**Describe the bug**
I am currently integrating the AWS Amplify library into my android application. I want to leverage the login / authentication features. I followed the [Amplify docs](https://aws-amplify.github.io/docs/android/authentication) and I ran `amlify init` , `amplify auth add`,  `amplify push`. I got no errors during the setup. The application crashes when i run it because the `initalize` call for the `AWSMobileClient` is looking for `./src/main/res/raw/awsconfiguration.json`. I tried re-running the setup,  changing how I specified the `/res` folder but the file is not apart of the project, 

**To Reproduce**
1. run $amplify add auth 
2. run $amplify push
3. add the AWSMobileClient init call to the Android app's MainActivity
4. Run the mobie app

**Which AWS service(s) are affected?**
Amplify Cli 

**Expected behavior**
a `awsconfiguration.json` file should be added to the android application `./src/main/res/raw` directory 
**Screenshots**
![screen shot 2018-11-16 at 4 12 19 pm](https://user-images.githubusercontent.com/3647217/48648040-e4b4a400-e9bb-11e8-8bef-7d8fb9535f19.png)

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
amplify --version
0.1.34
aws --version
aws-cli/1.15.56 Python/3.6.3 Darwin/17.7.0 botocore/1.10.55

android :
	compileSdkVersion 28
	buildToolsVersion "28.0.3"
        minSdkVersion 23
        targetSdkVersion 28

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

Nexus 6P API 23 simulator 

**Additional context**
I do see all the resources created on my AWS account

**Comment by muellerfr** [comment]
Hello @virtualprodigy,

there was an error in our documentation that I just fixed with this PR: https://github.com/aws-amplify/docs/pull/204

The awsconfiguration.json file is located in './app/src/main/res/raw'. I just validated the steps myself. Please see if you can find it there and let us know if you have any problems.

**Comment by virtualprodigy** [comment]
Hey @muellerfr ,
  yeah, that totally helped. I realized I put entered in the path to `res` without the ./`app`. After I ran  `ampligy init` again things started working. Thank you for the rapid support!

**Comment by harshikanu** [comment]
I am facing this issue. My awsconfiguration.json file is in app/src/main/res/raw/awsconfiguration.json but when I run the app, it still shows the same error. 
![image](https://user-images.githubusercontent.com/50932623/167699009-6aa66658-6eb4-4042-9b33-f234ab55bfd7.png)

**Comment by poojamat** [comment]
@harshikanu Sorry to hear that you are experiencing a problem with amplify. Could you please verify which amplify library are you using?

**Comment by harshikanu** [comment]
@poojamat Thanks for responding back. I am using 8.1.0 version.

**Comment by poojamat** [comment]
@harshikanu this repo is for amplify libraries. Could you please post your problem [here](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-android/issues).
